1.

In [ ]:
import numpy as np

In [ ]:
# 1. Buat matriks X berukuran 2x3
X = np.array([[10, 20, 30], [40, 50, 60]])
print("Matriks X:\n", X)

Matriks X:
 [[10 20 30]
 [40 50 60]]


In [ ]:
# Tampilkan ukuran dari matriks X
print("Ukuran matriks X:", X.shape)

Ukuran matriks X: (2, 3)


In [ ]:
# Tampilkan seluruh elemen dari kolom pertama (index 0)
print("Kolom pertama:", X[:, 0])

Kolom pertama: [10 40]


In [ ]:
# Tampilkan seluruh elemen dari baris kedua (index 1)
print("Baris kedua:", X[1, :])

Baris kedua: [40 50 60]


2. Ulangi soal no 1 menggunakan pytorch

In [ ]:
import torch

In [ ]:
# Membuat matrix 2x3
X = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
print("Matriks X:\n", X)

Matriks X:
 tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# Menampilkan ukuran matrix
print("Ukuran matrix X:", X.shape)


Ukuran matrix X: torch.Size([2, 3])


In [ ]:
# Menampilkan kolom pertama
print("Kolom pertama:", X[:, 0])


Kolom pertama: tensor([1, 4])


In [ ]:
# Menampilkan baris kedua
print("Baris kedua:", X[1, :])

Baris kedua: tensor([4, 5, 6])


Ulangi soal no 1 menggunakan tensorflow

In [ ]:
import tensorflow as tf

In [ ]:
# Membuat matrix 2x3
X = tf.constant([[1, 2, 3],
                 [4, 5, 6]])
print("Matriks X:\n", X)

Matriks X:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
# Menampilkan ukuran matrix
print("Ukuran matrix X:", X.shape)

Ukuran matrix X: (2, 3)


In [ ]:
# Menampilkan kolom pertama
print("Kolom pertama:", X[:, 0])

Kolom pertama: tf.Tensor([1 4], shape=(2,), dtype=int32)


In [ ]:
# Menampilkan baris kedua
print("Baris kedua:", X[1, :])

Baris kedua: tf.Tensor([4 5 6], shape=(3,), dtype=int32)
