**SOAL NO.1**

In [ ]:
import numpy as np

# buat vector x dengan ukuran 3x1
x = np.array([[1], [2], [3]])

# hitung panjang vector x
panjang = len(x)
print("Vector x:\n", x)
print("\nPanjang vector x:", panjang)

# tampilkan ukuran vector x
print("\nUkuran x:", x.shape)

# tampilkan tipe data dari vector x
print("\nTipe data x:", type(x))

# akses elemen pertama dari vector x
elemen_pertama = x[0][0]
print("\nElemen pertama:", elemen_pertama)

# tampilkan tipe data elemen pertama dari vector x
print("\nTipe data elemen pertama:", type(elemen_pertama))

Vector x:
 [[1]
 [2]
 [3]]

Panjang vector x: 3

Ukuran x: (3, 1)

Tipe data x: <class 'numpy.ndarray'>

Elemen pertama: 1

Tipe data elemen pertama: <class 'numpy.int64'>


**SOAL NO.2**

In [ ]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
print("Transpose x:\n", x_t)

# tampilkan ukuran dari vector x_t
print("\nUkuran x_t:", x_t.shape)

#lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[4], [5], [6]])

y_t = y.T
print("Transpose y:\n", y_t)

# tampilkan ukuran dari vector y_t
print("\nUkuran y_t:", y_t.shape)

Transpose x:
 [[1 2 3]]

Ukuran x_t: (1, 3)
Transpose y:
 [[4 5 6]]

Ukuran y_t: (1, 3)


**SOAL NO.3 MENGGUNAKAN TENSORFLOW**

In [ ]:
import tensorflow as tf

x = tf.Variable([[1], [2], [3]])

x_t = tf.transpose(x)

print("\nx:", x)
print("Ukuran x:", x.shape)

print("\nx_t:", x_t)
print("Ukuran x_t:", x_t.shape)

y = tf.Variable([[4], [5], [6]])
y_t = tf.transpose(y)

print("\ny:", y)
print("Ukuran y:", y.shape)

print("\ny_t:", y_t)
print("Ukuran y_t:", y_t.shape)


x: <tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[1],
       [2],
       [3]], dtype=int32)>
Ukuran x: (3, 1)

x_t: tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
Ukuran x_t: (1, 3)

y: <tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[4],
       [5],
       [6]], dtype=int32)>
Ukuran y: (3, 1)

y_t: tf.Tensor([[4 5 6]], shape=(1, 3), dtype=int32)
Ukuran y_t: (1, 3)


**SOAL NO.3 MENGGUNAKAN PYTORCH**

In [ ]:
import torch

x = torch.tensor([[1], [2], [3]])

x_t = x.T

print("\nx:", x)
print("Ukuran x:", x.shape)

print("\nx_t:", x_t)
print("Ukuran x_t:", x_t.shape)

y = torch.tensor([[4], [5], [6]])

y_t = y.T

print("\ny:", y)
print("Ukuran y:", y.shape)

print("\ny_t:", y_t)
print("Ukuran y_t:", y_t.shape)


x: tensor([[1],
        [2],
        [3]])
Ukuran x: torch.Size([3, 1])

x_t: tensor([[1, 2, 3]])
Ukuran x_t: torch.Size([1, 3])

y: tensor([[4],
        [5],
        [6]])
Ukuran y: torch.Size([3, 1])

y_t: tensor([[4, 5, 6]])
Ukuran y_t: torch.Size([1, 3])
