In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

fro_norm = np.linalg.norm(A, 'fro')

print("Matrix A:\n", A)
print("Frobenius Norm:", fro_norm)


Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Frobenius Norm: 16.881943016134134


In [ ]:
import torch

A_pt = torch.tensor([[1., 2., 3.],
                     [4., 5., 6.],
                     [7., 8., 9.]])

fro_norm_pt = torch.norm(A_pt, p='fro')

print("Matrix A:\n", A_pt)
print("Frobenius Norm:", fro_norm_pt)


Matrix A:
 tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
Frobenius Norm: tensor(16.8819)


In [ ]:
import tensorflow as tf

A_tf = tf.constant([[1., 2., 3.],
                    [4., 5., 6.],
                    [7., 8., 9.]])

fro_norm_tf = tf.norm(A_tf)

print("Matrix A:\n", A_tf)
print("Frobenius Norm:", fro_norm_tf.numpy())


Matrix A:
 tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], shape=(3, 3), dtype=float32)
Frobenius Norm: 16.881943
