**lakukan perhitungan soal excercise menggunakan collab**



1.   **lakukan perkalian dengan tensor di bawah ini**




In [ ]:
import numpy as np
import torch

# MENGGUNAKAN NUMPY
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])

b = np.array([[-1],
              [1],
              [-2]])

t = np.dot(a, b)
print(f"perkalian tensor menggunakan numpy: \n{t}")


# MENGGUNAKAN PYTORCH
A = torch.tensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

B = torch.tensor([[-1],
                  [1],
                  [-2]])

T = torch.matmul(A, B)
print(f"\nperkalian tensor menggunakan pytorch: \n{T}")

perkalian tensor menggunakan numpy: 
[[ -3]
 [ -9]
 [-15]]

perkalian tensor menggunakan pytorch: 
tensor([[ -3],
        [ -9],
        [-15]])





2.   **ulangi soal 1, dengan mengganti matrixnya dengan matrix I3, (identitas 3 x3)**



In [ ]:
import numpy as np
import torch

# MENGGUNAKAN NUMPY
a = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

b = np.array([[-1],
              [1],
              [-2]])

t = np.dot(a, b)
print(f"perkalian tensor menggunakan numpy: \n{t}")


# MENGGUNAKAN PYTORCH
A = torch.tensor([[1, 0, 0],
                  [0, 1, 0],
                  [0, 0, 1]])

B = torch.tensor([[-1],
                  [1],
                  [-2]])

T = torch.matmul(A, B)
print(f"\nperkalian tensor menggunakan pytorch: \n{T}")

perkalian tensor menggunakan numpy: 
[[-1]
 [ 1]
 [-2]]

perkalian tensor menggunakan pytorch: 
tensor([[-1],
        [ 1],
        [-2]])




3.   **lakukan perkalian dengan tensor di bawah ini**



In [ ]:
import numpy as np
import torch

# MENGGUNAKAN NUMPY
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])

b = np.array([[-1, 0],
              [1, 1],
              [-2, 2]])

t = np.dot(a, b)
print(f"perkalian tensor menggunakan numpy: \n{t}")


# MENGGUNAKAN PYTORCH
A = torch.tensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

B = torch.tensor([[-1, 0],
                  [1, 1],
                  [-2, 2]])


T = torch.matmul(A, B)
print(f"\nperkalian tensor menggunakan pytorch: \n{T}")

perkalian tensor menggunakan numpy: 
[[ -3   5]
 [ -9  14]
 [-15  23]]

perkalian tensor menggunakan pytorch: 
tensor([[ -3,   5],
        [ -9,  14],
        [-15,  23]])
