Soal No 1.

In [ ]:
import numpy as np
# buat matrix A dengan ukuran 2x3 dan vector b berukuran 3x1 menggunakan numpy
A = np.array([[12, 2, 7], [9, 5, 3]])
b = np.array([[2], [8], [19]])

print("Matrix A:")
print(A)

print("\nVector b:")
print(b)

Matrix A:
[[12  2  7]
 [ 9  5  3]]

Vector b:
[[ 2]
 [ 8]
 [19]]


In [ ]:
import torch
# buat matrix A_pt dengan ukuran 2x3 dan vector b_pt berukuran 3x1 menggunakan pytorch
A_pt = torch.tensor([[12, 2, 7], [9, 5, 3]])
b_pt = torch.tensor([[2], [8], [19]])

print("Matrix A_pt:")
print(A_pt)

print("\nVector b_pt:")
print(b_pt)

Matrix A_pt:
tensor([[12,  2,  7],
        [ 9,  5,  3]])

Vector b_pt:
tensor([[ 2],
        [ 8],
        [19]])


In [ ]:
import tensorflow as tf
# buat matrix A_tf dengan ukuran 2x3 dan vector b_tf berukuran 3x1 menggunakan tensorflow
A_tf = tf.Variable([[12, 2, 7], [9, 5, 3]])
b_tf = tf.Variable([[2], [8], [19]])

print("Matrix A_tf:")
print(A_tf)

print("\nVector b_tf:")
print(b_tf)

Matrix A_tf:
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[12,  2,  7],
       [ 9,  5,  3]], dtype=int32)>

Vector b_tf:
<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[ 2],
       [ 8],
       [19]], dtype=int32)>


In [ ]:
# kalikan matrix A_pt dengan vector b_pt
A_ptb_pt = torch.matmul(A_pt, b_pt)

print("Hasil kali A_pt dengan b_pt adalah:")
print(A_ptb_pt)

Hasil kali A_pt dengan b_pt adalah:
tensor([[173],
        [115]])


In [ ]:
# kalikan matrix A_tf dengan vector b_tf
A_tfb_tf = tf.matmul(A_tf, b_tf)

print("Hasil kali A_tf dengan b_tf adalah:")
print(A_tfb_tf)

Hasil kali A_tf dengan b_tf adalah:
tf.Tensor(
[[173]
 [115]], shape=(2, 1), dtype=int32)


Soal No 4

In [ ]:
# buat matrix B dengan ukuran 3x3 menggunakan numpy
B = np.array([[3, 1, 4], [9, 8, 6], [7, 2, 10]])

print("Matrix B:")
print(B)

Matrix B:
[[ 3  1  4]
 [ 9  8  6]
 [ 7  2 10]]


In [ ]:
# buat matrix B_pt dengan ukuran 3x3 menggunakan pytorch
B_pt = torch.tensor([[3, 1, 4], [9, 8, 6], [7, 2, 10]])

print("Matrix B_pt:")
print(B_pt)

Matrix B_pt:
tensor([[ 3,  1,  4],
        [ 9,  8,  6],
        [ 7,  2, 10]])


In [ ]:
# buat matrix B_tf dengan ukuran 3x3 menggunakan tensorflow
B_tf = tf.Variable([[3, 1, 4], [9, 8, 6], [7, 2, 10]])

print("Matrix B_tf:")
print(B_tf)

Matrix B_tf:
<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[ 3,  1,  4],
       [ 9,  8,  6],
       [ 7,  2, 10]], dtype=int32)>


Soal No 5

In [ ]:
# kalikan matrix A dengan matrix B
AB = np.dot(A, B)

print("Hasil kali Matrix A dengan B adalah:")
print(AB)

Hasil kali Matrix A dengan B adalah:
[[103  42 130]
 [ 93  55  96]]


In [ ]:
# kalikan matrix A_pt dengan matrix B_pt
A_ptB_pt = torch.matmul(A_pt, B_pt)

print("Hasil kali A_pt dengan B_pt adalah:")
print(A_ptB_pt)

Hasil kali A_pt dengan B_pt adalah:
tensor([[103,  42, 130],
        [ 93,  55,  96]])


In [ ]:
# kalikan matrix A_tf dengan matrix B_tf
A_tfB_tf = tf.matmul(A_tf, B_tf)

print("Hasil kali A_tf dengan B_tf adalah:")
print(A_tfB_tf)

Hasil kali A_tf dengan B_tf adalah:
tf.Tensor(
[[103  42 130]
 [ 93  55  96]], shape=(2, 3), dtype=int32)


Soal No 6

In [ ]:
# pembuktian apakah perkalian matrix bersifat komutatif (AB=BA) atau tidak
AB = np.dot(A, B)
AB

array([[103,  42, 130],
       [ 93,  55,  96]])

In [ ]:
BA = np.dot(B, A)
BA

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
print("perkalian matriks tidak bersifat komutatif maka dari itu AB tidak sama dengan BA")
print("BA error karena ukuran kolom dan barisnya tidak cocok")

perkalian matriks tidak bersifat komutatif maka dari itu AB tidak sama dengan BA
BA error karena ukuran kolom dan barisnya tidak cocok
