Soal No 1.


In [ ]:
import numpy as np
# buatlah matriks simetris dengan ukuran 3x3 dan buktikan bahwa itu merupakan matriks simetris
X_sym = np.array([[1, 2, 3], [2, 4, 5], [3, 5, 6]])
X_sym


array([[1, 2, 3],
       [2, 4, 5],
       [3, 5, 6]])

In [ ]:
X_sym.T

array([[1, 2, 3],
       [2, 4, 5],
       [3, 5, 6]])

In [ ]:
X_sym.T == X_sym

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Soal No 2.

In [ ]:
import torch
# menggunakan pytorch, buatlah matriks identitas I dengan ukuran 4x4
I = torch.tensor([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
I

tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

In [ ]:
# menggunakan pytorch, buatlah vector b_pt dengan ukuran 4x1
b_pt = torch.tensor([[22], [20], [16], [27]])
b_pt

tensor([[22],
        [20],
        [16],
        [27]])

In [ ]:
# kalikan matrix I dengan vector b_pt
Ib_pt = torch.matmul(I, b_pt)
Ib_pt

tensor([[22],
        [20],
        [16],
        [27]])