**The Hadamard Product**

**Soal No. 1**

In [ ]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy

import numpy as np

X = np.array([[1, 2, 3], [4, 5, 6]])

print(f"matrix X:")
print(X)

matrix X:
[[1 2 3]
 [4 5 6]]


In [ ]:
# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch

import torch

X_pt = torch.tensor([[7, 8, 9], [10, 11, 12]])

print(f"matrix X_pt:")
print(X_pt)

matrix X_pt:
tensor([[ 7,  8,  9],
        [10, 11, 12]])


In [ ]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow

import tensorflow as tf

X_tf = tf.constant([[13, 14, 15], [16, 17, 18]])

print(f"matrix X_ft:")
print(X_tf)

matrix X_ft:
tf.Tensor(
[[13 14 15]
 [16 17 18]], shape=(2, 3), dtype=int32)




*   lakukan perkalian matrix X, X_pt dan X_tf dengan suatu skalar



In [ ]:
# perkalian matrix X dengan suatu skalar

print(f"hasil perkalian matrix X dengan 2 adalah \n{X * 2}")

hasil perkalian matrix X dengan 2 adalah 
[[ 2  4  6]
 [ 8 10 12]]


In [ ]:
# perkalian matrix X_pt dengan suatu skalar

print(f"hasil perkalian matrix X_pt dengan 2 adalah \n{X_pt * 2}")

hasil perkalian matrix X_pt dengan 2 adalah 
tensor([[14, 16, 18],
        [20, 22, 24]])


In [ ]:
# perkalian matrix X_pt dengan suatu skalar

print(f"hasil perkalian matrix X_tf dengan 2 adalah \n{X_tf * 2}")

hasil perkalian matrix X_tf dengan 2 adalah 
[[26 28 30]
 [32 34 36]]




*  lakukan penjumlahan matrix X, X_pt dan X_tf dengan suatu skalar




In [ ]:
# penjumlahan matrix X dengan suatu skalar

print(f"hasil penjumlahan matrix X dengan 2 adalah \n{X + 2}")

hasil penjumlahan matrix X dengan 2 adalah 
[[3 4 5]
 [6 7 8]]


In [ ]:
# penjumlahan matrix X_pt dengan suatu skalar

print(f"hasil penjumlahan matrix X_pt dengan 2 adalah \n{X_pt + 2}")

hasil penjumlahan matrix X_pt dengan 2 adalah 
tensor([[ 9, 10, 11],
        [12, 13, 14]])


In [ ]:
# penjumlahan matrix X_tf dengan suatu skalar

print(f"hasil penjumlahan matrix X_tf dengan 2 adalah \n{X_tf + 2}")

hasil penjumlahan matrix X_tf dengan 2 adalah 
[[15 16 17]
 [18 19 20]]




*   lakukan pengurangan matrix X, X_pt dan X_tf dengan suatu skalar



In [ ]:
# pengurangan matriks X dengan suatu skalar

print(f"hasil pengurangan matrix X dengan 2 adalah \n{X-2}")

hasil pengurangan matrix X dengan 2 adalah 
[[-1  0  1]
 [ 2  3  4]]


In [ ]:
# pengurangan matriks X_pt dengan suatu skalar

print(f"hasil pengurangan matrix X_pt dengan 2 adalah \n{X_pt - 2}")

hasil pengurangan matrix X_pt dengan 2 adalah 
tensor([[ 5,  6,  7],
        [ 8,  9, 10]])


In [ ]:
# pengurangan matriks X_tf dengan suatu skalar

print(f"hasil pengurangan matrix X_tf dengan 2 adalah \n{X_tf - 2}")

hasil pengurangan matrix X_tf dengan 2 adalah 
[[11 12 13]
 [14 15 16]]


**Soal No. 2**

In [ ]:
# buat matrix Y dengan ukuran 2x3 menggunakan numpy

import numpy as np

Y = np.array([[1, 2, 3], [4, 5, 6]])

print(f"matrix Y: \n{Y}")

matrix Y: 
[[1 2 3]
 [4 5 6]]


In [ ]:
# buat matrix Y_pt dengan ukuran 2x3 menggunakan pytorch

import torch

Y_pt = torch.tensor([[7, 8, 9], [10, 11, 12]])

print(f"matrix Y_pt menggunakan pytorch: \n{Y_pt}")

matrix Y_pt menggunakan pytorch: 
tensor([[ 7,  8,  9],
        [10, 11, 12]])


In [ ]:
# buat matrix Y_tf dengan ukuran 2x3 menggunakan tensorflow

import tensorflow as tf

Y_tf = tf.Variable([[13, 14, 15], [16, 17, 18]])

print(f"matrix Y_tf menggunakan tensorflow: \n{Y_tf}")

matrix Y_tf menggunakan tensorflow: 
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[13, 14, 15],
       [16, 17, 18]], dtype=int32)>


In [ ]:
# kalikan matrix X dengan Y

print(f"hasil perkalian matrix X dengan matriks Y adalah \n{X * Y}")

hasil perkalian matrix X dengan matriks Y adalah 
[[ 1  4  9]
 [16 25 36]]


In [ ]:
#	kalikan matrix X_pt dengan Y_pt

print(f"hasil perkalian matrix X_pt dengan matriks Y_pt adalah \n{X_pt * Y_pt}")

hasil perkalian matrix X_pt dengan matriks Y_pt adalah 
tensor([[ 49,  64,  81],
        [100, 121, 144]])


In [ ]:
# kalikan matrix X_tf dengan Y_tf

print(f"hasil perkalian matrix X_tf dengan matriks Y_tf adalah \n{X_tf * Y_tf}")

hasil perkalian matrix X_tf dengan matriks Y_tf adalah 
[[169 196 225]
 [256 289 324]]
