**Soal No. 1**

In [ ]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy

import numpy as np

X = np.array([[1, 2, 3],
              [4, 5, 6]])

print(X)

matrix X:
[[1 2 3]
 [4 5 6]]


In [ ]:
# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
import torch

X_pt = torch.tensor([[7, 8, 9], [10, 11, 12]])

print(f"matrix X_pt menggunakam pytorch:")
print(X_pt)

matrix X_pt menggunakam pytorch:
tensor([[ 7,  8,  9],
        [10, 11, 12]])


In [ ]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
import tensorflow as tf

X_tf = tf.Variable([[13, 14, 15], [16, 17, 18]])

print(f"matrix X_tf menggunakan tensorflow:")
print(X_tf)

matrix X_tf menggunakan tensorflow:
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[13, 14, 15],
       [16, 17, 18]], dtype=int32)>


**Soal No. 2**

In [ ]:
# lakukan transpose pada matrix X, X_pt dan X_tf

XT = X.T

print(f"transpose dari matrix X adalah: \n{XT}")

transpose dari matrix X adalah: 
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# transpose pada X_pt

X_ptT = X_pt.T

print(f"transpose dari matrix X_pt adalah: \n{X_ptT}")

transpose dari matrix X_pt adalah: 
tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])


In [ ]:
# transpose pada X_tf

X_tfT = tf.transpose(X_tf)

print(f"transpose dari matrix X_tf adalah: \n{X_tfT}")

transpose dari matrix X_tf adalah: 
[[13 16]
 [14 17]
 [15 18]]
