**Soal No. 1**

In [1]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy

import numpy as np

X = np.array([[1, 2, 3], [4, 5, 6]])

print(f"matrix X: \n{X}")

matrix X: 
[[1 2 3]
 [4 5 6]]


In [2]:
# hitung berapa hasil penjumlahan elemen matrix X dengan fungsi sum

print(f"hasil penjumlahan seluruh elemen matrix X adalah {X.sum()}")

hasil penjumlahan seluruh elemen matrix X adalah 21


In [3]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow

import tensorflow as tf

X_tf = tf.Variable([[7, 8, 9], [10, 11, 12]])

print(f"matrix X_tf: \n{X_tf}")

matrix X_tf: 
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>


**Soal No. 2**

In [4]:
# hitung hasil penjumlahan seluruh elemen matrix X

print(f"hasil penjumlahan seluruh elemen matrix X adalah {X.sum()}")

hasil penjumlahan seluruh elemen matrix X adalah 21


In [5]:
# hitung hasil penjumlahan seluruh elemen matrix X_pt

import torch

X_pt = torch.tensor([[13, 14, 15], [16, 17, 18]])

print(f"hasil penjumlahan seluruh elemen matrix X_pt adalah {torch.sum(X_pt)}")

hasil penjumlahan seluruh elemen matrix X_pt adalah 93


In [6]:
# hitung hasil penjumlahan seluruh elemen matrix X_tf

print(f"hasil penjumlahan seluruh elemen matrix X_tf adalah {tf.reduce_sum(X_tf)}")

hasil penjumlahan seluruh elemen matrix X_tf adalah 57


**Soal No. 3**

In [7]:
# hitung hasil penjumlahan matrix X berdasarkan row nya

print(f"hasil penjumlahan seluruh kolom dari matrix X adalah, matrix X: {X.sum(axis=1)}")

hasil penjumlahan seluruh kolom dari matrix X adalah, matrix X: [ 6 15]


In [8]:
# hitung hasil penjumlahan matrix X_pt berdasarkan row nya

print(f"hasil penjumlahan seluruh kolom dari matrix X_pt adalah, matrix X_pt: {torch.sum(X_pt, axis=1)}")

hasil penjumlahan seluruh kolom dari matrix X_pt adalah, matrix X_pt: tensor([42, 51])


In [9]:
# hitung hasil penjumlahan matrix X_tf berdasarkan row nya

print(f"hasil penjumlahan seluruh kolom dari matrix X_ft adalah, matrix X_ft: {tf.reduce_sum(X_tf, axis=1)}")

hasil penjumlahan seluruh kolom dari matrix X_ft adalah, matrix X_ft: [24 33]


**Soal No. 4**

In [10]:
# hitung hasil penjumlahan matrix X berdasarkan kolom nya

print("4. Penjumlahan kolom X     :", np.sum(X, axis=0))

4. Penjumlahan kolom X     : [5 7 9]


In [ ]:
# hitung hasil penjumlahan matrix X_pt berdasarkan kolom nya

print("4. Penjumlahan kolom X_pt  :", torch.sum(X_pt, dim=0).numpy())

4. Penjumlahan kolom X_pt  : [29 31 33]


In [ ]:
# hitung hasil penjumlahan matrix X_tf berdasarkan kolom nya

print("4. Penjumlahan kolom X_tf  :", tf.reduce_sum(X_tf, axis=0).numpy())

**Soal No. 5**

In [ ]:
# hitung nilai minimal dari matrix X, X_pt dan X_tf

print("5. Nilai minimal  -> X:", np.min(X), "| X_pt:", torch.min(X_pt).item(), "| X_tf:", tf.reduce_min(X_tf).numpy())

5. Nilai minimal  -> X: 1 | X_pt: 13 | X_tf: 7


In [ ]:
# hitung nilai maksimal dari matrix X, X_pt dan X_tf

print("5. Nilai maksimal -> X:", np.max(X), "| X_pt:", torch.max(X_pt).item(), "| X_tf:", tf.reduce_max(X_tf).numpy())

5. Nilai maksimal -> X: 6 | X_pt: 18 | X_tf: 12


In [ ]:
# hitung nilai rata-rata dari matrix X, X_pt dan X_tf

print("5. Rata-rata      -> X:", np.mean(X), "| X_pt:", torch.mean(X_pt.float()).item(), "| X_tf:", tf.reduce_mean(X_tf).numpy())

5. Rata-rata      -> X: 3.5 | X_pt: 15.5 | X_tf: 9


**Soal No. 6**

In [ ]:
# # hitung hasil perkalian seluruh elemen matrix X

print("6. Perkalian elemen X      :", np.prod(X))

6. Perkalian elemen X      : 720


In [ ]:
# hitung hasil perkalian seluruh elemen matrix X_pt

print("6. Perkalian elemen X_pt   :", torch.prod(X_pt).item())

6. Perkalian elemen X_pt   : 13366080


In [ ]:
# hitung hasil perkalian seluruh elemen matrix X_tf

print("6. Perkalian elemen X_tf   :", tf.reduce_prod(X_tf).numpy())