Soal 1

In [ ]:
import numpy as np
import torch
import tensorflow as tf

In [ ]:
# buat vector x dan y dengan ukuran 1x3 menggunakan numpy
import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x)
print(y)

[1 2 3]
[4 5 6]


In [ ]:
# buat vector x_pt dan y_pt dengan ukuran 1x3 menggunakan pytorch
import torch

x_pt = torch.tensor([1, 2, 3])
y_pt = torch.tensor([4, 5, 6])

print(x_pt)
print(y_pt)

tensor([1, 2, 3])
tensor([4, 5, 6])


In [ ]:
# buat vector x_tf dan y_tf dengan ukuran 1x3 menggunakan tensorflow
import tensorflow as tf

x_tf = tf.constant([1, 2, 3])
y_tf = tf.constant([4, 5, 6])

print(x_tf)
print(y_tf)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


Soal 2

In [ ]:
# hitung perkalian dot product antara vector x dan vector y
dot_np = np.dot(x, y)
print(dot_np)

32


In [ ]:
# hitung perkalian dot product antara vector x_pt dan vector y_pt
dot_pt = torch.dot(x_pt, y_pt)
print(dot_pt)

tensor(32)


In [ ]:
# hitung perkalian dot product antara vector x_tf dan vector y_tf
dot_tf = tf.tensordot(x_tf, y_tf, axes=1)
print(dot_tf.numpy())

32


Soal 3

Soal Gambar

```
# lakukan perhitungan excercise menggunakan collab
```



In [ ]:
Y = [[42, 4, 7, 99],
     [-99, -3, 17, 22]]

In [ ]:
Y = np.array([[42, 4, 7, 99],
              [-99, -3, 17, 22]])

Y_T = Y.T
print(Y_T)

[[ 42 -99]
 [  4  -3]
 [  7  17]
 [ 99  22]]


In [ ]:
A = [[25, 10],
     [-2, 1]]

B = [[-1, 7],
     [10, 8]]

In [ ]:
A = np.array([[25, 10],
              [-2, 1]])

B = np.array([[-1, 7],
              [10, 8]])

H = A * B
print(H)

[[-25  70]
 [-20   8]]


In [ ]:
w = [-1, 2, -2]
x = [5, 10, 0]

In [ ]:
w = np.array([-1, 2, -2])
x2 = np.array([5, 10, 0])

hasil = np.dot(w, x2)
print(hasil)

15
